name: ZMK Custom Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Config Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build gperf ccache dfu-util device-tree-compiler wget \
            python3-pip python3-setuptools python3-wheel xz-utils file make gcc gcc-multilib \
            libncurses-dev libffi-dev libssl-dev libusb-1.0-0-dev
          pip3 install west
          pip3 install pyelftools

      - name: Install Zephyr SDK
        run: |
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.4/zephyr-sdk-0.16.4_linux-x86_64.tar.xz
          tar -xf zephyr-sdk-0.16.4_linux-x86_64.tar.xz
          mv zephyr-sdk-0.16.4 $HOME/zephyr-sdk
          $HOME/zephyr-sdk/setup.sh -t all -h
          echo "ZEPHYR_TOOLCHAIN_VARIANT=zephyr" >> $GITHUB_ENV
          echo "ZEPHYR_SDK_INSTALL_DIR=$HOME/zephyr-sdk" >> $GITHUB_ENV

      - name: Cache Zephyr & Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.west
            ~/zephyrproject
            ~/.cache
          key: ${{ runner.os }}-zmk-${{ hashFiles('**/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-zmk-

      - name: Initialize West
        run: |
          west init -l config
          west update
          west zephyr-export

      - name: Build SeaSide39 Right (master)
        run: |
          west build -s zmk/app -d build/right -b seeeduino_xiao_ble -- -DSHIELD=SeaSide39_R -DZMK_CONFIG=${{ github.workspace }}/config

      - name: Build SeaSide39 Left (peripheral)
        run: |
          west build -s zmk/app -d build/left -b seeeduino_xiao_ble -- -DSHIELD=SeaSide39_L -DZMK_CONFIG=${{ github.workspace }}/config

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/right/zephyr/zmk.uf2
            build/left/zephyr/zmk.uf2
